import './globals.css'
import { Inter } from 'next/font/google'
import Nav from './Nav'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className='bg-zinc-100 '>
        <Nav/>
        {children}</body>
    </html>
  )
}
